AWSTemplateFormatVersion: '2010-09-09'
Description: Eczema backend infrastructure (DynamoDB, SQS, IAM, Lambda, API Gateway)

Resources:
  # ---------------- DynamoDB tables ----------------
  SymptomLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SymptomLogs_Iac
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH    # partition key
        - AttributeName: id
          KeyType: RANGE   # sort key

  EnvCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EnvCache_Iac
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: city
          AttributeType: S
      KeySchema:
        - AttributeName: city
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  # ---------------- SQS queue ----------------
  SymptomQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SymptomQueue_Iac

  # ---------------- IAM role for all Lambdas ----------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eczema-backend-lambda-role-iac
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess

  # ---------------- Lambda functions (skeletons) ----------------
  EnvironmentDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: EnvironmentDataFunction_Iac
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          ENV_CACHE_TABLE: !Ref EnvCacheTable
      Code:
        ZipFile: |
          export const handler = async (event) => {
            console.log("Placeholder EnvironmentDataLambda", JSON.stringify(event));
            return { statusCode: 200, body: JSON.stringify({ message: "placeholder" }) };
          };

  SymptomLogsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SymptomLogsFunction_Iac
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          SYMPTOM_TABLE: !Ref SymptomLogsTable
          SYMPTOM_LOG_QUEUE_URL: !Ref SymptomQueue
      Code:
        ZipFile: |
          export const handler = async (event) => {
            console.log("Placeholder SymptomLogsLambda", JSON.stringify(event));
            return { statusCode: 202, body: JSON.stringify({ message: "queued (placeholder)" }) };
          };

  SymptomConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SymptomConsumerFunction_Iac
      Runtime: nodejs22.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          SYMPTOM_TABLE: !Ref SymptomLogsTable
      Code:
        ZipFile: |
          export const handler = async (event) => {
            console.log("Placeholder SymptomConsumerLambda", JSON.stringify(event));
            return {};
          };

  # Event source mapping so consumer reads from SQS
  SymptomQueueEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt SymptomQueue.Arn
      FunctionName: !Ref SymptomConsumerLambda
      BatchSize: 10
      Enabled: true

#-------------------COGNITO IAM--------------------
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EczemaCognitoAuthRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref CognitoIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": "authenticated"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser


#----------------------COGNITO--------------------------
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: EczemaUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: EczemaUserPoolClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: EczemaIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !Sub "cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
          ServerSideTokenCheck: false
  
  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthRole.Arn


# ---------------- API Gateway (REST) ----------------
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: EczemaBackendApi_Iac

  # /LiveEnvironmentDataFunction
  LiveEnvResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: LiveEnvironmentDataFunction
      
  LiveEnvAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref LiveEnvResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          -  { LambdaArn: !GetAtt EnvironmentDataLambda.Arn }
          
  LiveEnvOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref LiveEnvResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""

  # /SymptomLogsFunction
  SymptomLogsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: SymptomLogsFunction

  SymptomLogsAnyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SymptomLogsResource
      HttpMethod: ANY
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiGatewayCognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - { LambdaArn: !GetAtt SymptomLogsLambda.Arn }
          
  SymptomLogsOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SymptomLogsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,POST'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""

  # /SymptomLogsFunction/{id} DELETE
  SymptomLogsIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !Ref SymptomLogsResource
      PathPart: "{id}"

  SymptomLogsIdDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SymptomLogsIdResource
      HttpMethod: DELETE
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref ApiGatewayCognitoAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - { LambdaArn: !GetAtt SymptomLogsLambda.Arn }
          
  SymptomLogsIdOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref SymptomLogsIdResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,DELETE'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true


  # Permissions for API Gateway to call Lambdas
  EnvironmentLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EnvironmentDataLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/POST/LiveEnvironmentDataFunction

  SymptomLogsLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SymptomLogsLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/SymptomLogsFunction*
      
  SymptomLogsDeletePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SymptomLogsLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/DELETE/SymptomLogsFunction/*

  ApiGatewayCognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: EczemaCognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref ApiGatewayRestApi
      ProviderARNs:
        - !GetAtt CognitoUserPool.Arn

  # Deployment + stage
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - LiveEnvAnyMethod
      - LiveEnvOptionsMethod
      - SymptomLogsAnyMethod
      - SymptomLogsIdDeleteMethod
      - SymptomLogsOptionsMethod
      - SymptomLogsIdOptionsMethod

    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: prod


Outputs:
  LambdaExecutionRoleArn:
    Description: IAM role ARN used by Lambda functions
    Value: !GetAtt LambdaExecutionRole.Arn

  EnvironmentDataLambdaArn:
    Description: Environment Lambda ARN
    Value: !GetAtt EnvironmentDataLambda.Arn

  SymptomLogsLambdaArn:
    Description: Symptom logs Lambda ARN
    Value: !GetAtt SymptomLogsLambda.Arn

  SymptomConsumerLambdaArn:
    Description: Symptom consumer Lambda ARN
    Value: !GetAtt SymptomConsumerLambda.Arn

  ApiBaseUrl:
    Description: Base invoke URL for the prod stage
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: Cognito User Pool App Client ID
    Value: !Ref CognitoUserPoolClient

  CognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref CognitoIdentityPool


